<?php
/**
 * Implements hook_help().
 */
function navionics_help($path, $arg) {
  switch ($path) {
    case "admin/help#navionics":
      return '<p>' . t("About Navionics web API") . '</p>';
      break;
  }
}


/**
 * Implements hook_init().
 */
function navionics_init() {
  $navionics_web_api_server = variable_get('navionics_web_api_server', 0);

  if ($navionics_web_api_server === '1') {
    // Temporarily we add the JS directly in html.tpl.php
    //drupal_add_js('http://webapi-dev.navionics.io/dist/webapi/webapi.min.no-dep.js', array('type'=>'external', 'weight' => -100));
    drupal_add_css('http://webapi-dev.navionics.io/dist/webapi/webapi.min.css', array('type'=>'external', 'weight' => -100));
  } else {
    // Temporarily we add the JS directly in html.tpl.php
    //drupal_add_js('http://webapiv2.navionics.com/dist/webapi/webapi.min.no-dep.js', array('type'=>'external', 'weight' => -100));
    drupal_add_css('http://webapiv2.navionics.com/dist/webapi/webapi.min.css', array('type'=>'external', 'weight' => -100));
  }
}


/**
 * Implements template_preprocess_html().
 */
function navionics_preprocess_html(&$variables) {
  $navionics_web_api_server = variable_get('navionics_web_api_server', 0);

  if ($navionics_web_api_server === '1') {
    $variables['attributes_array']['data-root']='http://webapi-dev.navionics.io/dist/webapi/images';
  } else {
    $variables['attributes_array']['data-root']='http://webapiv2.navionics.com/dist/webapi/images';
  }
}


/**
 * Implements hook_menu().
 */
function navionics_menu() {
  $items = array();

  $items['admin/config/system/navionics'] = array(
    'title' => 'Navionics web API',
    'description' => 'Configure Navionics web API settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('navionics_admin_form'),
    'access arguments' => array('administer navionics'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function navionics_permission() {
  return array(
    'administer navionics' => array(
      'title' => t('Administer Navionics web API'),
      'description' => t('Administer Navionics web API'),
    ),
  );
}


/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function navionics_admin_form($form, &$form_state) {

  $form['conf'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Navionics API settings'),
  );

  $form['conf']['navionics_web_api_server'] = array(
    '#type'          => 'radios',
    '#title'         => t('Navionics web API server'),
    '#default_value' => variable_get('navionics_web_api_server', 0),
    '#options'       =>
      array(
        0 => t('Live <i>http://webapiv2.navionics.com</i> (default)'),
        1 => t('Dev <i>http://webapi-dev.navionics.io</i>')
      ),
    '#description'   => t('On a production site, always use the live server.'),
  );

  return system_settings_form($form);
}
