<?php
/**
 * Implements hook_help().
 */
function navionics_web_api_help($path, $arg) {
  switch ($path) {
    case "admin/help#navionics":
      return '<p>' . t("About Navionics web API") . '</p>';
      break;
  }
}


/**
 * Implements hook_init().
 */
function navionics_web_api_init() {
  $navionics_web_api_server = variable_get('navionics_web_api_server', 0);

  if ($navionics_web_api_server === '1') {
    drupal_add_js('//webapi-dev.navionics.io/dist/webapi/webapi.min.no-dep.js?v=2.1.8', array('type'=>'external', 'weight' => -100));
    drupal_add_css('//webapi-dev.navionics.io/dist/webapi/webapi.min.css?v=2.1.8', array('type'=>'external', 'weight' => 1000));
  } elseif ($navionics_web_api_server === '2') {
    drupal_add_js('//webapi-beta.navionics.io/dist/webapi/webapi.min.no-dep.js', array('type'=>'external', 'weight' => -100));
    drupal_add_css('//webapi-beta.navionics.io/dist/webapi/webapi.min.css', array('type'=>'external', 'weight' => 1000));
  } else {
    drupal_add_js('//webapiv2.navionics.com/dist/webapi/webapi.min.no-dep.js?v=2.1.8', array('type'=>'external', 'weight' => -100));
    drupal_add_css('//webapiv2.navionics.com/dist/webapi/webapi.min.css?v=2.1.8', array('type'=>'external', 'weight' => 1000));
  }
}


/**
 * Implements template_preprocess_html().
 */
function navionics_web_api_preprocess_html(&$variables) {
  $navionics_web_api_server = variable_get('navionics_web_api_server', 0);

  if ($navionics_web_api_server === '1') {
    $variables['attributes_array']['data-root']='//webapi-dev.navionics.io/dist/webapi/images';
  } else if ($navionics_web_api_server === '2') {
    $variables['attributes_array']['data-root']='//webapi-beta.navionics.io/dist/webapi/images';
  } else {
    $variables['attributes_array']['data-root']='//webapiv2.navionics.com/dist/webapi/images';
  }
}

/**
 * Implements hook_menu().
 */
function navionics_web_api_menu() {
  $items = array();

  $items['admin/config/system/navionics_web_api'] = array(
    'title' => 'Navionics web API',
    'description' => 'Configure Navionics web API settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('navionics_web_api_admin_form'),
    'access arguments' => array('administer navionics'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function navionics_web_api_permission() {
  return array(
    'administer navionics' => array(
      'title' => t('Administer Navionics web API'),
      'description' => t('Administer Navionics web API'),
    ),
  );
}


/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function navionics_web_api_admin_form($form, &$form_state) {

  $form['conf']['server'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Navionics API settings'),
  );

  $form['conf']['server']['navionics_web_api_server'] = array(
    '#type'          => 'radios',
    '#title'         => t('Navionics web API server'),
    '#default_value' => variable_get('navionics_web_api_server', 0),
    '#options'       =>
      array(
        0 => t('Live <i>http://webapiv2.navionics.com</i> (default)'),
        1 => t('Dev  <i>http://webapi-dev.navionics.io</i>'),
        2 => t('Beta <i>http://webapi-beta.navionics.io</i>')
      ),
    '#description'   => t('On a production site, always use the live server.'),
  );

  $form['conf']['pages'] = array(
    '#type'  => 'fieldset',
    '#title' => t('Use Navionics maps on specific pages'),
  );

  $form['conf']['pages']['navionics_web_api_server'] = array();

  return system_settings_form($form);
}
